version: '3.3'
services:

  cyber-ui:
    image: cybernode/cui-browser:latest
    ports:
      - 32500:80
    environment:
       CYBER_CHAINGEAR_API: http://chaingear-api:32600
       CYBER_SEARCH_API: http://cs-search-api:10300
       CYBER_MARKETS_API: http://cm-rest-api:32800
       CYBER_MARKETS_STREAM_API: ws://cm-stream-api:32801
