version: '3.3'
services:

  cs-chain-pumps-eth-btc-bth-etc:
    container_name: pump-eth-btc-bth-etc
    image: cybernode/cs-chain-pumps:dev
    restart: unless-stopped
    environment:
      CASSANDRA_HOSTS: elassandra
      CS_CHAINS_TO_PUMP: ETHEREUM,BITCOIN,BITCOIN_CASH,ETHEREUM_CLASSIC
      KAFKA_BROKERS: kafka:9092
      PARITY_ETH_URL: http://parity_eth:8545
      BITCOIND_URL: http://cyber:cyber@bitcoind:8332
      ABC_URL: http://bitcoin:password@abc:7332
      PARITY_ETC_URL: http://parity_etc:8545
      CS_LOG_LEVEL: INFO

  cs-search-api:
    container_name: search-api
    ports:
      - 32901:10300
    image: cybernode/cs-search-api:latest
    restart: unless-stopped
    environment:
      CASSANDRA_HOSTS: elassandra
      CS_LOG_LEVEL: INFO
      CORS_ALLOWED_ORIGINS: "*"

  cs-address-service:
    container_name: address-service
    image: cybernode/address-service:latest
    restart: unless-stopped
    environment:
      CASSANDRA_HOSTS: elassandra
      KAFKA_BROKERS: kafka:9092
      CS_LOG_LEVEL: INFO

networks:
    default:
        external:
            name: staging_default
