FROM buildpack-deps:jessie-scm

# install Rust
# `sh -s -- -y` passes -y parameter to piped script
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH $PATH:/root/.cargo/bin

COPY 01build.sh .
RUN chmod +x 01build.sh && ./01build.sh

VOLUME /build

# run time copy built binaries to provided /build volume
CMD cp --verbose ./target/release/* /build
