version: '3.3'
services:

  elassandra:
    container_name: elassandra
    image: strapdata/elassandra:5.5.0.8
    restart: always
    volumes:
      - /cyberdata/staging/elassandra/lib:/var/lib/cassandra
      - /cyberdata/staging/elassandra/log:/var/log/cassandra
    environment:
      CASSANDRA_DC: DEVELOPMENT
      CASSANDRA_CLUSTER_NAME: CYBER_SEARCH
    ports:
      - "9042:9042"
      - "9200:9200"
      - "9300:9300"